export const typeGradients = {
    normal: "linear-gradient(#A8A77A, #B8B8A8)",
    fire: "linear-gradient(#EE8130, #FFA07A)",
    water: "linear-gradient(#6390F0, #7198F5)",
    electric: "linear-gradient(#F7D02C, #F7E07C)",
    grass: "linear-gradient(#7AC74C, #84D96C)",
    ice: "linear-gradient(#96D9D6, #A6E9E6)",
    fighting: "linear-gradient(#C22E28, #D24E3E)",
    poison: "linear-gradient(#A33EA1, #B35EB1)",
    ground: "linear-gradient( #E2BF65, #E2CF85)",
    flying: "linear-gradient(#3dc7ef 50%, #bdb9b8 50%)",
    psychic: "linear-gradient( #F95587, #FA75A3)",
    bug: "linear-gradient( #A6B91A, #B6C92A)",
    rock: "linear-gradient( #B6A136, #C6B146)",
    ghost: "linear-gradient( #735797, #8376A7)",
    dragon: "linear-gradient( #53a4cf, #f16e57)",
    dark: "linear-gradient(#705746, #806766)",
    steel: "linear-gradient( #B7B7CE, #C7C7DE)",
    fairy: "linear-gradient( #D685AD, #E695BD)",
  };
  
  export const typeTextColors = {
    normal: "black",
    fire: "white",
    water: "white",
    electric: "black",
    grass: "black",
    ice: "black",
    fighting: "white",
    poison: "white",
    ground: "black",
    flying: "black",
    psychic: "white",
    bug: "black",
    rock: "black",
    ghost: "white",
    dragon: "white",
    dark: "white",
    steel: "black",
    fairy: "black",
  };
  